const QuestionActionTypes = {
  SUBMIT_QUESTIONS_START: 'SUBMIT_QUESTIONS_START',
  SUBMIT_QUESTIONS_SUCCESS: 'SUBMIT_QUESTIONS_SUCCESS',
  SUBMIT_QUESTIONS_FAILURE: 'SUBMIT_QUESTIONS_FAILURE',
  FETCH_QUESTIONS_START: 'FETCH_QUESTIONS_START',
  FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
  FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE',
}

export default QuestionActionTypes;
