const FeedbackActionTypes = {
  SUBMIT_FEEDBACK_START: 'SUBMIT_FEEDBACK_START',
  SUBMIT_FEEDBACK_SUCCESS: 'SUBMIT_FEEDBACK_SUCCESS',
  SUBMIT_FEEDBACK_FAILURE: 'SUBMIT_FEEDBACK_FAILURE',
}

export default FeedbackActionTypes;
